### ISSUE TITLE
Is there any protocol for whole genome sequencing data?

### ISSUE THREAD

**Issue by y9c** [etal/cnvkit-examples#1]
I wonder weather there is a example to apply cnvkit in whole genome sequencing data.

**Comment by etal** [comment]
Not here, since the files would be large. But I think there's an example in bcbio-nextgen to run it on the 1000 Genomes NA12878 data.

**Comment by y9c** [comment]
If I want to manipulate the data in na12878, which manual should I follow? I only found bed file in that folder.
Should I run `make` before I start these examples. 

---

``` shell
$make

......
Traceback (most recent call last):
  File "/usr/local/bin/cnvkit.py", line 4, in <module>
    __import__('pkg_resources').run_script('CNVkit==0.7.5.dev0', 'cnvkit.py')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 745, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1677, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/CNVkit-0.7.5.dev0-py2.7.egg/EGG-INFO/scripts/cnvkit.py", line 11, in <module>

  File "build/bdist.linux-x86_64/egg/cnvlib/commands.py", line 576, in _cmd_fix

  File "build/bdist.linux-x86_64/egg/cnvlib/commands.py", line 589, in do_fix

  File "build/bdist.linux-x86_64/egg/cnvlib/fix.py", line 25, in load_adjust_coverages
  File "build/bdist.linux-x86_64/egg/cnvlib/fix.py", line 89, in match_ref_to_probes
ValueError: Reference is missing 19402 bins found in CL_seq
make: *** [build/CL_seq_flat.cnr] Error 1
```

**Comment by etal** [comment]
The files in the na12878 in this repo are work in progress, and it's going to be an example for whole exome sequencing, not whole genome. But WGS analysis is fairly straightforward, and you don't need any special data to do the analysis from scratch:
1. Download the NA12878 whole-genome sequencing reads as a BAM file from your preferred source (e.g. ENA, [Illumina](http://www.illumina.com/platinumgenomes/)).
2. Download the corresponding reference genome GRCh37, if you don't already have it. Scan it with `cnvkit.py access` to produce a BED file. This will be both the "access" and "target" BED file.
3. Create an empty file to use as the "antitarget" BED": `touch empty.bed`
4. Run CNVkit on this genome with the `batch` command, specifying the e.g. `cnvkit.py batch NA12878.bam -n -f GRCh37.fasta -g access.g37.bed -t access.g37.bed -a empty.bed --annotate refFlat.txt --split --target-avg-size 1000`
5. The segmentation by CBS will probably be noisy, so try repeating segmentation with a stricter p-value threshold: `cnvkit.py segment NA12878.cnr -t 1e5`

**Comment by charliecurnin** [comment]
Hi @etal! Thanks—the steps above were very helpful. I'm wondering, though, whether I need some copy number reference file (like a .cnn), one that gives the expected DOC for each region. Even though the DOC for WGS should be more uniform, doesn't CNVkit need some way of determining what the DOC is supposed to be? Or what the copy number is in the normal population?

**Comment by etal** [comment]
Sure, @charliecurnin, you can create a reference .cnn from a pool of normal
samples.

See:
- https://cnvkit.readthedocs.io/en/stable/pipeline.html#reference
- https://cnvkit.readthedocs.io/en/stable/nonhybrid.html

Using a pooled reference is not required, but generally it will improve
your results.
